import re
import sqlite3
from pathlib import Path

try:
    from .config import get_settings
except ImportError:
    from config import get_settings


_FIRST_DB_ACCESS_LOGGED = False


class HybridRow(dict):
    def __init__(self, columns, values):
        super().__init__(zip(columns, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


class CursorWrapper:
    def __init__(self, cursor, *, engine, lastrowid=None):
        self._cursor = cursor
        self._engine = engine
        self.lastrowid = lastrowid if lastrowid is not None else getattr(cursor, "lastrowid", None)

    def _wrap_row(self, row):
        if row is None:
            return None
        if self._engine == "sqlite":
            return row
        columns = [item[0] for item in (self._cursor.description or [])]
        return HybridRow(columns, row)

    def fetchone(self):
        return self._wrap_row(self._cursor.fetchone())

    def fetchall(self):
        rows = self._cursor.fetchall()
        if self._engine == "sqlite":
            return rows
        columns = [item[0] for item in (self._cursor.description or [])]
        return [HybridRow(columns, row) for row in rows]

    @property
    def rowcount(self):
        return getattr(self._cursor, "rowcount", -1)


def _split_statements(script):
    statements = []
    buffer = []
    in_string = False
    quote = ""
    for char in script:
        if char in {"'", '"'}:
            if not in_string:
                in_string = True
                quote = char
            elif quote == char:
                in_string = False
        if char == ";" and not in_string:
            statement = "".join(buffer).strip()
            if statement:
                statements.append(statement)
            buffer = []
            continue
        buffer.append(char)
    tail = "".join(buffer).strip()
    if tail:
        statements.append(tail)
    return statements


def _replace_qmarks(sql):
    result = []
    in_string = False
    prev = ""
    for char in sql:
        if char == "'" and prev != "\\":
            in_string = not in_string
        if char == "?" and not in_string:
            result.append("%s")
        else:
            result.append(char)
        prev = char
    return "".join(result)


def _replace_datetime_literal(match):
    raw = match.group(1).strip()
    sign = "-" if raw.startswith("-") else "+"
    interval = raw.lstrip("+-")
    return f"(CURRENT_TIMESTAMP {sign} INTERVAL '{interval}')"


def _translate_sql(sql, engine):
    if engine == "sqlite":
        return sql

    translated = str(sql)
    translated = re.sub(r"PRAGMA\s+foreign_keys\s*=\s*ON\s*;?", "", translated, flags=re.IGNORECASE)
    # DATE('now') → CURRENT_DATE (SQLite-only, not valid in Postgres)
    translated = re.sub(r"DATE\s*\(\s*'now'\s*\)", "CURRENT_DATE", translated, flags=re.IGNORECASE)
    # DATETIME('now') → CURRENT_TIMESTAMP
    translated = re.sub(r"DATETIME\s*\(\s*'now'\s*\)", "CURRENT_TIMESTAMP", translated, flags=re.IGNORECASE)
    translated = re.sub(
        r"DATETIME\s*\(\s*'now'\s*,\s*'([^']+)'\s*\)",
        _replace_datetime_literal,
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"DATETIME\s*\(\s*'now'\s*,\s*\?\s*\)",
        "(CURRENT_TIMESTAMP + CAST(? AS INTERVAL))",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", translated, flags=re.IGNORECASE)
    if "ON CONFLICT" not in translated.upper() and "INSERT INTO" in translated.upper() and "INSERT OR IGNORE" in str(sql).upper():
        translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    translated = translated.replace("AUTOINCREMENT", "")
    translated = translated.replace("DATETIME", "TIMESTAMP")
    translated = translated.replace("INTEGER PRIMARY KEY", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    translated = translated.replace("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    translated = _replace_qmarks(translated)
    return translated


class DatabaseConnection:
    def __init__(self, connection, *, engine):
        self._connection = connection
        self.engine = engine

    def execute(self, sql, params=()):
        translated_sql = _translate_sql(sql, self.engine)
        cursor = self._connection.cursor()
        cursor.execute(translated_sql, params or ())
        lastrowid = getattr(cursor, "lastrowid", None)
        if self.engine == "postgres" and translated_sql.lstrip().upper().startswith("INSERT ") and cursor.rowcount:
            try:
                probe = self._connection.cursor()
                probe.execute("SELECT LASTVAL()")
                value = probe.fetchone()
                lastrowid = value[0] if value else None
                probe.close()
            except Exception:
                lastrowid = None
        return CursorWrapper(cursor, engine=self.engine, lastrowid=lastrowid)

    def executescript(self, script):
        if self.engine == "sqlite":
            return self._connection.executescript(script)
        cursor = self._connection.cursor()
        for statement in _split_statements(script):
            translated = _translate_sql(statement, self.engine)
            if translated.strip():
                cursor.execute(translated)
        return cursor

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def connect():
    global _FIRST_DB_ACCESS_LOGGED
    settings = get_settings()
    if not _FIRST_DB_ACCESS_LOGGED:
        print("DB FIRST ACCESS:", settings.db_engine)
        _FIRST_DB_ACCESS_LOGGED = True
    if settings.db_engine == "postgres":
        import psycopg2
        import psycopg2.extras

        connection = psycopg2.connect(settings.database_url)
        return DatabaseConnection(connection, engine="postgres")

    raw_url = settings.database_url
    if raw_url.startswith("sqlite:///"):
        db_path = raw_url.replace("sqlite:///", "", 1)
        candidate = Path(db_path)
        if not candidate.is_absolute():
            candidate = (Path(__file__).resolve().parent.parent / candidate).resolve()
        candidate.parent.mkdir(parents=True, exist_ok=True)
        connection = sqlite3.connect(str(candidate), timeout=15.0)
    elif raw_url.startswith("file:"):
        connection = sqlite3.connect(raw_url, timeout=15.0, uri=True)
    else:
        candidate = Path(raw_url)
        if not candidate.is_absolute():
            candidate = (Path(__file__).resolve().parent.parent / candidate).resolve()
        candidate.parent.mkdir(parents=True, exist_ok=True)
        connection = sqlite3.connect(str(candidate), timeout=15.0)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return DatabaseConnection(connection, engine="sqlite")
